name: Pre-commit auto-update

on:
  # every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    uses: observeinc/.github/.github/workflows/pre-commit-autoupdate.yaml@main
    secrets: inherit